### ISSUE TITLE
好兄弟

### ISSUE THREAD

**Issue by CNDrwei** [ydf0509/auto_restart#1]
哥们你有这么多工具， 能不能整个web框架像sanic flask 那样，通过rest-x 整理出一个极易开发的框架，无论是并发，自动化测试，文档，日志，连接数据库的工具，都封装好，这样就极大的方便了python web开发，且工具都很牛逼～

**Comment by ydf0509** [comment]
数据库连接池  https://github.com/ydf0509/mysql_pool

**Comment by ydf0509** [comment]
qq群  189603256

**Comment by CNDrwei** [comment]
> 哥们你有这么多工具， 能不能整个web框架像sanic flask 那样，通过rest-x 整理出一个极易开发的框架，无论是并发，自动化测试，文档，日志，连接数据库的工具，都封装好，这样就极大的方便了python web开发，且工具都很牛逼～
