### ISSUE TITLE
建议像supervisor安装好后加入开机自启动的方式以及apt、yum安装方式

### ISSUE THREAD

**Issue by DJMIN** [ydf0509/auto_restart#2]
大牛有时间的话可以考虑考虑，像supervisor安装好后加入开机自启动的方式以及apt、yum安装方式

**Comment by ydf0509** [comment]
用screen比supervisor更合适，这种一般放在测试环境运行就性能，不要部署到生产上。生产自动发版有点危险

**Comment by ydf0509** [comment]
你把这个命令部署到supervisor就可以了
